// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAIAgent.Infrastructure.Persistence;

#nullable disable

namespace SmartAIAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartAIAgentDbContext))]
    [Migration("20260828102031_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStage");

                    b.HasIndex("RequirementId");

                    b.HasIndex("Status");

                    b.ToTable("AgentRuns", (string)null);
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("Status");

                    b.ToTable("Approvals", (string)null);
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("Requirements", (string)null);
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.UserStory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.ToTable("UserStories", (string)null);
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.UserStoryAcceptanceCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserStoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("UserStoryId");

                    b.ToTable("UserStoryAcceptanceCriteria", (string)null);
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FromStage")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ToStage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("WorkflowEvents", (string)null);
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.AgentRun", b =>
                {
                    b.HasOne("SmartAIAgent.Domain.Entities.Requirement", "Requirement")
                        .WithMany("AgentRuns")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.Approval", b =>
                {
                    b.HasOne("SmartAIAgent.Domain.Entities.AgentRun", "AgentRun")
                        .WithMany("Approvals")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentRun");
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.UserStory", b =>
                {
                    b.HasOne("SmartAIAgent.Domain.Entities.Requirement", "Requirement")
                        .WithMany("UserStories")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.UserStoryAcceptanceCriterion", b =>
                {
                    b.HasOne("SmartAIAgent.Domain.Entities.UserStory", "UserStory")
                        .WithMany("AcceptanceCriteria")
                        .HasForeignKey("UserStoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserStory");
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.WorkflowEvent", b =>
                {
                    b.HasOne("SmartAIAgent.Domain.Entities.AgentRun", "AgentRun")
                        .WithMany("WorkflowEvents")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentRun");
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.AgentRun", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("WorkflowEvents");
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.Requirement", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("UserStories");
                });

            modelBuilder.Entity("SmartAIAgent.Domain.Entities.UserStory", b =>
                {
                    b.Navigation("AcceptanceCriteria");
                });
#pragma warning restore 612, 618
        }
    }
}
